[build]
  publish = "public"
  functions = "functions"
  command = "yarn prod"
# command: ntl dev
[dev]
command = "hugo server --disableFastRender"
targetPort = 1313
framework = "#custom"
port = 3000
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

# Initial .env set at runtime, can be overriden , if deploy via cli
[template.environment]
  HUGO_BASEURL = "Site Url: https://yourdomain.com"

[build.environment]
  # hugo env
  HUGO_BASEURL = "https://pitlords.com"
  HUGO_VERSION = "0.83.1"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  # needed to be able to deploy in netlify using git hooks
  # set to theme if deploying via netlify-cli, if by git hooks retain the line below
  # environment = { HUGO_THEME = "repo" }

[context.dev]
  # locally build using: ntl build --context=dev
  # environment = { HUGO_THEME = "goldcoders" }

[context.deploy-preview]
  # locally build using: ntl build --context=deploy-preview
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --buildFuture"
