[build]
  publish = "public"
  functions = "functions"
  command = "hugo --gc --minify -b $HUGO_BASEURL"
# command: ntl dev
[dev]
command = "hugo serve --disableFastRender"
targetPort = 1313
framework = "#custom"
port = 3000
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

# Initial .env set at runtime, can be overriden , if deploy via cli
[template.environment]
  HUGO_BASEURL = "https://yourdomain.com"
  # needed by our payment processor
  PAYMONGO_EMAIL = "Paymongo Email"
  PAYMONGO_PASS = "Paymongo Password"
  PAYMONGO_LIVEMODE = "set to true on live site"
  # needed by our purchase spreadsheet
  GOOGLE_SPREADSHEET_ID_FROM_URL="Spreadsheet URL ID"
  GOOGLE_SERVICE_ACCOUNT_EMAIL="Google Service Account Email"
  GOOGLE_PRIVATE_KEY="Google Private Key"
  # needed by netlify cms
  LOGIN_LOGO_URL = "https://yourdomain.com/images/logo.svg"

[build.environment]
  # hugo env
  HUGO_BASEURL = "https://pitlords.com"
  HUGO_VERSION = "0.83.1+extended"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  # needed to be able to deploy in netlify using git hooks
  # set to theme if deploying via netlify-cli, if by git hooks retain the line below
  # environment = { HUGO_THEME = "repo" }

[context.dev]
  # locally build using: ntl build --context=dev
  # environment = { HUGO_THEME = "goldcoders" }

[context.deploy-preview]
  # locally build using: ntl build --context=deploy-preview
  command = "hugo serve --gc --minify -b $DEPLOY_PRIME_URL --buildFuture"
